export const FETCH_POSTS = "FETCH_POSTS"
export const FETCH_SINGLE_POST = "FETCH_SINGLE_POST"
export const FETCH_SINGLE_USER =  "FETCH_SINGLE_USER"
export const FETCH_POSTS_COMMENTS = "FETCH_POSTS_COMMENTS" 